backend:
  name: git-gateway
  branch: main

# For local development
local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "Hero Section"
        name: "hero"
        file: "content/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: "CTA Button Text", name: "cta_label", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      
      - label: "About Section"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      
      - label: "Impact Section"
        name: "impact"
        file: "content/impact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Content", name: "body", widget: "markdown" }


